---
title: "Satyr"
output:
  pdf_document: 
    toc: false
  word_document:
    toc: true
    reference_docx: templates/wordstyletemplate.docx
    keep_md: true
  html_document:
    css: css/tufte.css
    toc: true
    toc_float: true
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Mordenkainen Presents: Monsters of the Multiverse**

***Originating in the Feywild — a realm of pure emotion-satyrs thrive on the energy of merriment. They resemble elves but have goatlike legs, cloven hooves, and ram or goat horns. The magic of the fey realm has given them an innate ability to perform, to delight, and to resist magical intrusion. While they’re usually found in the Feywild, satyrs do wander to other planes of existence, most often to the Material Plane. There they seek to bring a bit of their home plane’s splendor to other worlds.***

-   **Ability Score Increase.** When determining your character’s ability scores, increase one score by 2 and increase a different score by 1, or increase three different scores by 1. You can't raise any of your scores above 20.

-   **Creature Type.** You are a Fey.

-   **Size.** You are Medium.

-   **Speed.** Your walking speed is 35 feet.

-   **Ram.** You can use your head and horns to make unarmed strikes. When you hit with them, the strike deals 1d6 + your Strength modifier bludgeoning damage, instead of the bludgeoning damage normal for an unarmed strike.

-   **Magic Resistance.** You have advantage on saving throws against spells.

-   **Mirthful Leaps.** Whenever you make a long jump or a high jump, you can roll a d8 and add the number rolled to the number of feet you cover, even when making a standing jump. This extra distance costs movement as normal.

-   **Reveler.** As an embodiment of revelry, you have proficiency in the Performance and Persuasion skills, and you have proficiency with one musical instrument of your choice.

-   **Languages.** Your character can speak, read, and write Common and one other language that you and your DM agree is appropriate for the character. The *Player’s Handbook* offers a list of languages to choose from. The DM is free to modify that list for a campaign.

\newpage

# **Mythic Odysseys of Theros**

***Satyrs have a well-earned reputation for their good spirits, gregarious personalities, and love of revels. Most satyrs are driven by simple desires, to see the world and to sample its every pleasure. While their spontaneity and whimsy sometimes put them at odds with more stoic peoples, satyrs rarely let the moodiness of others hinder their own happiness. Life is a blessing from the gods, after all, and the proper response to such a gift, as far as most satyrs are concerned, is to accept it with relish.***

-   **Ability Score Increase.** Your Charisma score increases by 2, and your Dexterity score increases by 1.

-   **Age.** Satyrs mature and age at about the same rate as humans.

-   **Alignment.** Satyrs delight in living a life free of the mantle of law. They gravitate toward being good, but some have devious streaks and enjoy causing dismay.

-   **Size.** Satyrs range from just under 5 feet to about 6 feet in height, with generally slender builds. Your size is medium.

-   **Speed.** Your base walking speed is 35 feet.

-   **Fey.** Your creature type is fey, rather than humanoid.

-   **Ram.** You can use your head and horns to make unarmed strikes. If you hit with them, you deal bludgeoning damage equal to 1d4 + your Strength modifier.

-   **Magic Resistance.** You have advantage on saving throws against spells and other magical effects.

-   **Mirthful Leaps.** Whenever you make a long or high jump, you can roll a d8 and add the number to the number of feet you cover, even when making a standing jump. This extra distance costs movement as normal.

-   **Reveler.** You have proficiency in the Performance and Persuasion skills, and you have proficiency with one musical instrument of your choice.

```{=html}
<!-- -->
```
-   **Languages.** You can speak, read, and write Common and Sylvan.
